
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: heroku_ex1
  pool: 5
  username: root
  password: root

# 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: heroku_ex1_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: heroku_ex1_production
  pool: 5
  username: root
  password: root
